workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Plagit Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.invain.mh
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Set code signing to manual
        script: |
          sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --no-codesign
      - name: Sign and export IPA
        script: |
          xcode-project use-profiles
          cd build/ios/archive
          xcodebuild -exportArchive \
            -archivePath Runner.xcarchive \
            -exportOptionsPlist $CM_EXPORT_OPTIONS_PATH \
            -exportPath ../ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true