exports.seed = async function (knex) {
  await knex('community_posts').del();
  await knex('featured_content').del();

  await knex('community_posts').insert([
    { title: '5 Things Recruiters Notice First on Your CV', category: 'Career Tips', author: 'Admin Mirko', author_initials: 'AM', status: 'published', is_pinned: true, is_featured_on_home: true, linked_employer: '', linked_job: '', published_date: '2026-03-20', views: 4231, saves: 678, read_time: '4 min', summary: 'Key tips for hospitality professionals.', avatar_hue: 0.50 },
    { title: 'Nobu Restaurant — Now Hiring in Dubai', category: 'Featured Employers', author: 'Admin Mirko', author_initials: 'AM', status: 'published', is_pinned: true, is_featured_on_home: true, linked_employer: 'Nobu Restaurant', linked_job: '', published_date: '2026-03-18', views: 1854, saves: 212, read_time: '2 min', summary: 'Explore careers at Nobu.', avatar_hue: 0.55 },
    { title: 'From Line Cook to Executive Chef in 3 Years', category: 'Success Stories', author: 'Elena Rossi', author_initials: 'ER', status: 'published', is_pinned: false, is_featured_on_home: false, linked_employer: '', linked_job: '', published_date: '2026-03-16', views: 2105, saves: 342, read_time: '6 min', summary: 'Elena shares her career progression.', avatar_hue: 0.52 },
    { title: 'Free Food Safety Certification — Level 2', category: 'Training', author: 'Admin Mirko', author_initials: 'AM', status: 'published', is_pinned: false, is_featured_on_home: false, linked_employer: '', linked_job: '', published_date: '2026-03-12', views: 980, saves: 156, read_time: '3 min', summary: 'Free government-accredited certification.', avatar_hue: 0.50 },
    { title: 'How to Negotiate Your Salary in Hospitality', category: 'Career Tips', author: 'Admin Mirko', author_initials: 'AM', status: 'published', is_pinned: false, is_featured_on_home: false, linked_employer: '', linked_job: '', published_date: '2026-03-11', views: 1450, saves: 234, read_time: '5 min', summary: 'Practical negotiation strategies.', avatar_hue: 0.50 },
    { title: 'The Ritz London — Premium Hiring Event', category: 'Featured Employers', author: 'Admin Mirko', author_initials: 'AM', status: 'published', is_pinned: false, is_featured_on_home: false, linked_employer: 'The Ritz London', linked_job: '', published_date: '2026-03-08', views: 1120, saves: 89, read_time: '2 min', summary: 'Exclusive hiring event.', avatar_hue: 0.68 },
    { title: 'Senior Chef — Nobu Dubai (Immediate Start)', category: 'Job Highlights', author: 'System', author_initials: 'SY', status: 'published', is_pinned: false, is_featured_on_home: false, linked_employer: 'Nobu Restaurant', linked_job: 'Senior Chef', published_date: '2026-03-22', views: 876, saves: 45, read_time: '1 min', summary: 'Featured job at Nobu Dubai.', avatar_hue: 0.55 },
    { title: 'Top 10 Interview Questions for Hospitality', category: 'Career Tips', author: 'Admin Mirko', author_initials: 'AM', status: 'draft', is_pinned: false, is_featured_on_home: false, linked_employer: '', linked_job: '', views: 0, saves: 0, read_time: '4 min', summary: 'Prepare for your next interview.', avatar_hue: 0.50 },
    { title: 'Bartender Certification Guide', category: 'Training', author: 'Admin Mirko', author_initials: 'AM', status: 'draft', is_pinned: false, is_featured_on_home: false, linked_employer: '', linked_job: '', views: 0, saves: 0, read_time: '5 min', summary: 'Complete bartender certification guide.', avatar_hue: 0.50 },
    { title: 'How I Landed My Dream Job at The Dorchester', category: 'Success Stories', author: 'Sofia Blanc', author_initials: 'SB', status: 'scheduled', is_pinned: false, is_featured_on_home: false, linked_employer: 'The Dorchester', linked_job: '', published_date: '2026-04-01', views: 0, saves: 0, read_time: '5 min', summary: 'Sofia\'s story.', avatar_hue: 0.62 },
    { title: 'Four Seasons — Global Hospitality Careers', category: 'Featured Employers', author: 'Admin Mirko', author_initials: 'AM', status: 'archived', is_pinned: false, is_featured_on_home: false, linked_employer: 'Four Seasons', linked_job: '', published_date: '2026-02-15', views: 2340, saves: 178, read_time: '3 min', summary: 'Global opportunities with Four Seasons.', avatar_hue: 0.52 },
  ]);

  await knex('featured_content').insert([
    { title: 'Nobu Restaurant — Now Hiring', type: 'Featured Employer', linked_entity: 'Nobu Restaurant', placement: 'Candidate Home', status: 'active', is_pinned: true, priority: 1, start_date: '2026-03-18', end_date: '2026-04-18', clicks: 342, views: 1854, avatar_hue: 0.55 },
    { title: 'The Ritz London Hiring Event', type: 'Featured Employer', linked_entity: 'The Ritz London', placement: 'Candidate Home', status: 'active', is_pinned: true, priority: 2, start_date: '2026-03-20', end_date: '2026-04-20', clicks: 218, views: 1120, avatar_hue: 0.68 },
    { title: 'Senior Chef — Immediate Start', type: 'Featured Job', linked_entity: 'Senior Chef — Nobu', placement: 'Jobs Page', status: 'active', is_pinned: false, priority: 3, start_date: '2026-03-22', end_date: '2026-04-22', clicks: 156, views: 876, avatar_hue: 0.55 },
    { title: 'Get Hired Faster This Week', type: 'Home Banner', linked_entity: '', placement: 'Candidate Home', status: 'active', is_pinned: true, priority: 1, start_date: '2026-03-15', end_date: '2026-04-15', clicks: 890, views: 3200, avatar_hue: 0.50 },
    { title: 'Top 5 CV Tips for Hospitality', type: 'Recommended', linked_entity: '5 Things Recruiters Notice', placement: 'Community', status: 'active', is_pinned: false, priority: 4, start_date: '2026-03-20', end_date: '2026-04-20', clicks: 234, views: 980, avatar_hue: 0.50 },
    { title: 'Welcome to Plagit', type: 'Onboarding Card', linked_entity: '', placement: 'Onboarding', status: 'active', is_pinned: false, priority: 5, start_date: '2026-01-01', clicks: 1200, views: 3159, avatar_hue: 0.50 },
    { title: 'Four Seasons — Premium Employer', type: 'Featured Employer', linked_entity: 'Four Seasons', placement: 'Candidate Home', status: 'scheduled', is_pinned: false, priority: 3, start_date: '2026-04-01', end_date: '2026-05-01', clicks: 0, views: 0, avatar_hue: 0.52 },
    { title: 'Bartender — Ritz London', type: 'Featured Job', linked_entity: 'Bartender — The Ritz', placement: 'Jobs Page', status: 'expired', is_pinned: false, priority: 0, start_date: '2026-03-01', end_date: '2026-03-15', clicks: 98, views: 456, avatar_hue: 0.68 },
    { title: 'Find Staff Near You', type: 'Home Banner', linked_entity: '', placement: 'Business Home', status: 'active', is_pinned: false, priority: 2, start_date: '2026-03-10', end_date: '2026-04-10', clicks: 145, views: 890, avatar_hue: 0.50 },
  ]);
};
