// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj8C1VcZWPlnRrHMc_2VjMLVZ3HmVxdWw',
    appId: '1:831689638350:web:2232d356fcb0da4bdd2b9f',
    messagingSenderId: '831689638350',
    projectId: 'mirko-hospitality-ea7e2',
    authDomain: 'mirko-hospitality-ea7e2.firebaseapp.com',
    storageBucket: 'mirko-hospitality-ea7e2.appspot.com',
    measurementId: 'G-9CYG79SDEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPRLpwsfdMj_R_K8UDIuDLCzP40_Dfy_U',
    appId: '1:831689638350:android:b238febdefb09240dd2b9f',
    messagingSenderId: '831689638350',
    projectId: 'mirko-hospitality-ea7e2',
    storageBucket: 'mirko-hospitality-ea7e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3DgkdtU1e9LMEdswS7EHmZ4_FlnDc6EE',
    appId: '1:831689638350:ios:3e92959c9aa4e49add2b9f',
    messagingSenderId: '831689638350',
    projectId: 'mirko-hospitality-ea7e2',
    storageBucket: 'mirko-hospitality-ea7e2.appspot.com',
    iosClientId: '831689638350-bme9b266v6vnp20295j6poehvm1hrevq.apps.googleusercontent.com',
    iosBundleId: 'com.invain.mh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3DgkdtU1e9LMEdswS7EHmZ4_FlnDc6EE',
    appId: '1:831689638350:ios:3e92959c9aa4e49add2b9f',
    messagingSenderId: '831689638350',
    projectId: 'mirko-hospitality-ea7e2',
    storageBucket: 'mirko-hospitality-ea7e2.appspot.com',
    iosClientId: '831689638350-bme9b266v6vnp20295j6poehvm1hrevq.apps.googleusercontent.com',
    iosBundleId: 'com.invain.mh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBad_Bw8lFwmMMEfKea1-HihR1cu0t7XY0',
    appId: '1:831689638350:web:fc746ad035bc5753dd2b9f',
    messagingSenderId: '831689638350',
    projectId: 'mirko-hospitality-ea7e2',
    authDomain: 'mirko-hospitality-ea7e2.firebaseapp.com',
    storageBucket: 'mirko-hospitality-ea7e2.appspot.com',
    measurementId: 'G-JHGEZSP31J',
  );
}
