const router = require('express').Router();
const { authenticate, requireAdmin } = require('../middleware/auth');
const c = require('../controllers/adminBusinessesController');
router.use(authenticate, requireAdmin);
router.get('/', c.list);
router.get('/:id', c.get);
router.patch('/:id/status', c.updateStatus);
router.patch('/:id/verify', c.setVerified);
router.patch('/:id/featured', c.setFeatured);
router.delete('/:id', c.remove);
module.exports = router;
