const router = require('express').Router();
const { authenticate, requireAdmin } = require('../middleware/auth');
const c = require('../controllers/adminCommunityController');
router.use(authenticate, requireAdmin);
router.get('/', c.list);
router.patch('/:id/status', c.updateStatus);
router.patch('/:id/pin', c.setPinned);
router.patch('/:id/feature', c.setFeaturedOnHome);
router.delete('/:id', c.remove);
module.exports = router;
