class CurrencyUtils {
  // Mapping of country names to their respective currency symbols
  static final Map<String, String> _currencyList = {
    "afghanistan": "\u{060B}",  // "؋"
    "albania": "L",
    "algeria": "دج",
    "argentina": "\$",
    "armenia": "֏",
    "australia": "\$",
    "austria": "€",
    "azerbaijan": "₼",
    "bahrain": ".د.ب",  // Encapsulated in quotes
    "bangladesh": "৳",
    "belarus": "Br",
    "belgium": "€",
    "brazil": "R\$",
    "bulgaria": "лв",
    "canada": "\$",
    "chile": "\$",
    "china": "¥",
    "colombia": "\$",
    "croatia": "kn",
    "czech republic": "Kč",
    "denmark": "kr",
    "egypt": "£",
    "eurozone": "€",
    "finland": "€",
    "france": "€",
    "germany": "€",
    "greece": "€",
    "hong kong": "\$",
    "hungary": "Ft",
    "iceland": "kr",
    "india": "₹",
    "indonesia": "Rp",
    "iran": "﷼",
    "iraq": "ع.د",
    "ireland": "€",
    "israel": "₪",
    "italy": "€",
    "japan": "¥",
    "jordan": "د.ا",
    "kazakhstan": "₸",
    "kenya": "Sh",
    "kuwait": "د.ك",
    "lebanon": "ل.ل",
    "malaysia": "RM",
    "mexico": "\$",
    "morocco": "د.م.",
    "netherlands": "€",
    "new zealand": "\$",
    "nigeria": "₦",
    "norway": "kr",
    "oman": "ر.ع.",
    "pakistan": "₨",
    "philippines": "₱",
    "poland": "zł",
    "portugal": "€",
    "qatar": "ر.ق",
    "romania": "lei",
    "russia": "₽",
    "saudi arabia": "﷼",
    "singapore": "\$",
    "south africa": "R",
    "south korea": "₩",
    "spain": "€",
    "sweden": "kr",
    "switzerland": "CHF",
    "taiwan": "NT\$",
    "thailand": "฿",
    "turkey": "₺",
    "united arab emirates": "د.إ",
    "united kingdom": "£",
    "united states": "\$",
    "vietnam": "₫",
    "default": "\$",
  };

  // Function to retrieve the currency symbol by country name
  static String? getCurrencySymbolByCountry(String countryName) {
    String normalizedCountryName = countryName.toLowerCase();
    return _currencyList[normalizedCountryName] ?? _currencyList["default"];
  }
}
